"""payment events idempotency fields

Revision ID: 02aba1bc691a
Revises: 42a25f96b645
Create Date: 2026-02-17 10:38:24.196003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aba1bc691a'
down_revision = '42a25f96b645'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_events', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('payment_events', sa.Column('provider_event_id', sa.String(length=255), nullable=True))
    op.add_column('payment_events', sa.Column('provider_order_id', sa.String(length=255), nullable=True))
    op.add_column('payment_events', sa.Column('provider_payment_id', sa.String(length=255), nullable=True))
    op.create_index('ix_payment_events_tenant_event', 'payment_events', ['tenant_id', 'provider_event_id'], unique=False)
    op.create_index('ix_payment_events_tenant_order', 'payment_events', ['tenant_id', 'provider_order_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_events_tenant_order', table_name='payment_events')
    op.drop_index('ix_payment_events_tenant_event', table_name='payment_events')
    op.drop_column('payment_events', 'provider_payment_id')
    op.drop_column('payment_events', 'provider_order_id')
    op.drop_column('payment_events', 'provider_event_id')
    op.drop_column('payment_events', 'tenant_id')
    # ### end Alembic commands ###

