"""payments module

Revision ID: 42a25f96b645
Revises: 525def7b4d32
Create Date: 2026-02-16 18:52:47.499210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a25f96b645'
down_revision = '525def7b4d32'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

