"""payment: add receipt/refund fields + FKs + indexes

Revision ID: 7b1892983079
Revises: 6ac0909ec73d
Create Date: 2026-02-17 12:59:53.446202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1892983079'
down_revision = '6ac0909ec73d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('branch_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index('ix_appt_tenant_branch', 'appointments', ['tenant_id', 'branch_id'], unique=False)
    op.create_index('ix_appt_tenant_branch_staff_start', 'appointments', ['tenant_id', 'branch_id', 'staff_user_id', 'start_at'], unique=False)
    op.create_foreign_key(None, 'appointments', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'appointments', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.add_column('branches', sa.Column('branch_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_branches_branch_id'), 'branches', ['branch_id'], unique=False)
    op.create_index('ix_payments_tenant_branch', 'branches', ['tenant_id', 'branch_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.add_column('payments', sa.Column('branch_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_payments_tenant_appt'), table_name='payments')
    op.create_index('ix_payments_tenant_appt', 'payments', ['tenant_id', 'appointment_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_index('ix_payments_tenant_appt', table_name='payments')
    op.create_index(op.f('ix_payments_tenant_appt'), 'payments', ['tenant_id', 'appointment_id'], unique=False)
    op.drop_column('payments', 'branch_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index('ix_payments_tenant_branch', table_name='branches')
    op.drop_index(op.f('ix_branches_branch_id'), table_name='branches')
    op.drop_column('branches', 'branch_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index('ix_appt_tenant_branch_staff_start', table_name='appointments')
    op.drop_index('ix_appt_tenant_branch', table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.drop_column('appointments', 'branch_id')
    # ### end Alembic commands ###

